# Generated by Django 4.2.15 on 2025-09-16 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("release_date", models.DateTimeField()),
            ],
            options={
                "ordering": ["name", "model"],
                "unique_together": {("name", "model")},
            },
        ),
    ]
