# Generated by Django 4.2.15 on 2025-09-16 08:35

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NetworkNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("country", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("street", models.CharField(max_length=100)),
                ("house", models.CharField(max_length=50)),
                (
                    "debt",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Задолженность перед поставщиком",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("level", models.PositiveSmallIntegerField(default=0, editable=False)),
                (
                    "products",
                    models.ManyToManyField(blank=True, related_name="nodes", to="network.product"),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        help_text="Поставщик (родительское звено)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="clients",
                        to="network.networknode",
                    ),
                ),
            ],
            options={
                "ordering": ["level", "name"],
            },
        ),
    ]
